ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'FINOPS';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CX';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'AUDITOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'COMPLIANCE';
